language: python
cache: pip
matrix:
    include:
      # - python: 3.4  # sphinx has dropped 3.4
      - python: 3.5
      - python: 3.6
      - python: 3.7
install:
  - pip install --upgrade pip wheel setuptools
  - pip install -e .[sphinx,testing]
before_script:
    - (cd test/commonmark && ./spec.sh)
script:
    - pytest -v --cov=mistletoe --cov-report=
after_success:
    - coveralls
