language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install --upgrade pip wheel setuptools
  - pip install -e .[testing]
before_script:
    - (cd test/commonmark && ./spec.sh)
script:
    - pytest -v --cov=mistletoe --cov-report=
after_success:
    - coveralls
